### ISSUE TITLE
What is your home directory on PythonAnywhere?

### ISSUE THREAD

**Issue by alexbijak** [18F/an_introduction_to_python#4]
I am a bit stuck on using PythonAnywhere. When I type in import os and print(os.getcwd()) to figure out my current working directory, the line “/home/alexbijak” is returned. I’m confused as to where “alexbijak” is exactly. Is this just on the PythonAnywhere server? I should not be looking for anything on my local drive called “alexbijak”, right?

**Comment by EricSchles** [comment]
Sorry this is a little stale.  That's correct, `/home/alexbijak` is in PythonAnywhere.  PythonAnywhere does not have access to your local environment.
